### ISSUE TITLE
What is `features` in implementing a kill switch

### ISSUE THREAD

**Issue by mangelozzi** [popeindustries/sw-tips#3]
Firstly, what an amazing presentation, that is by far the most memorable and interesting coding talk I have ever seen. Big thank you! I come back and watch your video at least once a year. I have been working through your tips one by one.

I am stuck with this one: <https://github.com/popeindustries/sw-tips#add-a-feature-flagkill-switch>
Figured it out: the unregistration of the service worker happens in the client window, so the service worker does *not* need to see the features object and unregister itself. `features` is just some global object on the client `window` object.

PS: `burnDownTheHouse` is a pretty badass name for a function.

**Comment by popeindustries** [comment]
Thanks for the feedback! Glad you figured it out. Lot's more interesting ideas here too: https://stackoverflow.com/questions/33986976/how-can-i-remove-a-buggy-service-worker-or-implement-a-kill-switch/38980776#38980776
